import React from 'react';
import { 
    LayoutDashboard, 
    Car, 
    Calendar, 
    CircleDollarSign, 
    Settings, 
    Plus, 
    ChevronRight, 
    Wrench,
    FileText,
    Fuel,
    Users,
    TrendingUp,
    TrendingDown,
    X,
    Sun,
    Moon,
    Bell,
    LogOut,
    FileDown,
    BarChart3,
    MessageSquare,
    Upload,
    Download,
    MoreVertical,
    CalendarDays,
    Menu,
} from 'lucide-react';

export const ICONS = {
    dashboard: <LayoutDashboard className="h-5 w-5" />,
    fleet: <Car className="h-5 w-5" />,
    bookings: <Calendar className="h-5 w-5" />,
    finance: <CircleDollarSign className="h-5 w-5" />,
    reports: <BarChart3 className="h-5 w-5" />,
    settings: <Settings className="h-5 w-5" />,
    customers: <Users className="h-5 w-5" />,
    calendar: <CalendarDays className="h-5 w-5" />,
    add: <Plus className="h-5 w-5" />,
    right: <ChevronRight className="h-4 w-4" />,
    wrench: <Wrench className="h-4 w-4 text-text-secondary" />,
    document: <FileText className="h-4 w-4 text-text-secondary" />,
    fuel: <Fuel className="h-4 w-4 text-text-secondary" />,
    users: <Users className="h-6 w-6" />,
    income: <TrendingUp className="h-6 w-6 text-green-500" />,
    expense: <TrendingDown className="h-6 w-6 text-expense-500" />,
    close: <X className="h-6 w-6" />,
    sun: <Sun className="h-6 w-6" />,
    moon: <Moon className="h-6 w-6" />,
    notifications: <Bell className="h-6 w-6" />,
    logout: <LogOut className="h-5 w-5" />,
    export: <FileDown className="h-4 w-4" />,
    import: <Upload className="h-4 w-4" />,
    whatsapp: <MessageSquare className="h-4 w-4" />,
    menu: <Menu className="h-6 w-6" />,
    more: <MoreVertical className="h-5 w-5" />,
};